You are a robot with a gripper that can move objects to build a query structure.
The domain assumes a world where there are a set of blocks that can be positioned adjacent (left/right/front/behind/top/above) to each other, an arm that can hold one block at a time, and a table where blocks can be placed.
There are seven actions defined in this domain:
pickup: allows the arm to pick up a block if it is clear and the arm is empty. After the pickup action, the arm will be holding the block, and the block will no longer be on the table or clear.
putdown-left: allows the arm to put down a block to the left of another block if it is holding a block and the supporter block is clear. After the putdown-left action, the arm will be empty, and the block will be clear and positioned to the left of the specified supporter block.
putdown-right: allows the arm to put down a block to the right of another block if it is holding a block and the supporter block is clear. After the putdown-right action, the arm will be empty, and the block will be clear and positioned to the right of the specified supporter block.
putdown-front: allows the arm to put down a block in front of another block if it is holding a block and the supporter block is clear. After the putdown-front action, the arm will be empty, and the block will be clear and positioned in front of the specified supporter block.
putdown-behind: allows the arm to put down a block behind another block if it is holding a block and the supporter block is clear. After the putdown-behind action, the arm will be empty, and the block will be clear and positioned behind the specified supporter block.
stack-on-another: allows the arm to stack a block on top of another block if the arm is holding a block and the supporter block is clear. After the stack-directly action, the arm will be empty, the moved block will be positioned on top of the supporting block, and the supporting block will no longer be clear.
stack-above-two: allows the arm to stack a block on top of two supporting blocks. After the stack-above-two action, the arm will be empty, the moved block will positioned above both supporting blocks, and the supporting blocks will no longer be clear.
